leveling:
    power: 1.0 #set this to adjust the EXP curve (higher numbers equal longer ending levels)
    maxExperience: 100000 #be cautious on changing this after it has been set)
    maxLevel: 50 #max level to master/change from PARENT to Child)
    expLoss: 0.10 #exp loss on death, is taken from current LEVEL not ALL exp.
    max-tracked-blocks: 2000 #max blocks to track for no-exp
    block-tracking-duration: 900000 #duration to track for no-exp
    resetExpOnClassChange: true #will reset the exp if the player switches without mastering
    swapMasteryCost: false #will allow for users to change back to their mastered class freely
    partyBonus: 0.20 #cumulative bonus for each player after the first in a party
    levelsViaExpLoss: false #allow level loss when players lose xp
    masteryLoss: false #allow mastery loss when players lose xp
properties:
    iConomy: false #use of the cost system
    swapcost: 0 #cost to swap
    debug: false #use this at your own risk
    useDamageSystem: true #toggles the damage system
bed:
    bedHeal: true #Do you want players to heal in beds? NOTE - useDamageSystem must be true
    healInterval: 15 #the seconds it takes to heal the healPercent
    healPercent: 5 #the amount of damage to heal.
mana:
    regenInterval: 5 #time in seconds between regen ticks
    regenPercent: 5 #the percent regenned each tick
default:
    level: 1 #Level to use HATS!
    allowHatsPlugin: false
    prefixClassName: false
mappartyui:
    id: 1 #Map ID number, 0 or 1 is desired
    enabled: true
    packetinterval: 20 #Rate of packets
worlds:
    disabledWorlds: ['World1', 'World2', 'World3'] #If your worlds are in a seperate folder, include the path. E.g. 'worlds/world1'
