leveling:
    power: 1.0 #set this to adjust the EXP curve (higher numbers equal longer ending levels)
    maxExperience: 100000 #be cautious on changing this after it has been set)
    maxLevel: 50 #max level to master/change from PARENT to Child)
    expLoss: 0.10 #exp loss on death, is taken from current LEVEL not ALL exp.
    pvpExpLossMultiplier: 1.0 #exp loss multiplier used during pvp
    maxPartySize: 6 #maximum party size
    partyBonus: 1.0 #multiplier of how much bonus xp should be awarded overall to parties
    levelsViaExpLoss: false #allow level loss when players lose xp
    masteryLoss: false #allow mastery loss when players lose xp
    noSpawnCamp: false #allow xp gain when near a spawner if false
    spawnCampRadius: 7 #how close to the spawner the creature needs to be to deny xp
    spawnCampExpMult: .5 #if noSpawnCamp is true, all xp gained from killing is multiplied by this number. setting to 0 gives no xp.
    resetOnDeath: false #Hardcore mode to reset all levels/exp on death
    pvpLevelRange: 50 #Level that players must be within to PvP with each other
classes:
    swapcost: 0 #cost to swap
    oldClassSwapCost: 0 #cost to swap back to a class you already have xp in
    profSwapCost: 0 #cost to swap to a new profession
    oldProfSwapCost: 0 #cost to swap back to an old profession
    swapMasteryCost: false #will allow for users to change back to their mastered class freely
    firstSwitchFree: true #toggles charging for the first class switch
    prefixClassName: false #basic name prefixing of heroclass, may not work correctly
    resetExpOnClassChange: true #will reset the exp if the player switches without mastering
    resetMasteryOnClassChange: false #will reset all xp including masteries if the player switches classes
    resetProfMasteryOnClassChange: false #will reset all xp including masteries if the player switches professions
    resetProfOnPrimaryChange: false #will reset the players profession whenever they change primary classes
    lockPathTillMaster: false #Will make it so players can not switch classes until they have mastered their current class
    lockAtHighestTier: false #Will not allow a player who is the highest tier to swap classes
properties:
    storage-type: yml #currently only supports yml
    iConomy: false #use of the cost system
    debug: false #use this at your own risk
    enchant-exp-mult: 3 #XP cost multiplier for enchants - set to 0 to disable
    globalCooldown: 1 #Seconds a hero must wait before using a second skill
    block-tracking-duration: 900000 #duration to track for no-exp
    max-tracked-blocks: 2000 #max blocks to track for no-exp
    foodHealPercent: .05 # .05 = 5% of Total HP regained when a player regains health from being full
bed:
    bedHeal: true #Do you want players to heal in beds? NOTE - useDamageSystem must be true
    healInterval: 15 #the seconds it takes to heal the healPercent
    healPercent: 5 #the amount of damage to heal.
mana:
    regenInterval: 5 #time in seconds between regen ticks
    regenPercent: 5 #the percent regenned each tick
hats:
    level: 1 #Level to use HATS!
    allowHatsPlugin: false
worlds:
    disabledWorlds: ['World1', 'World2', 'World3'] #If your worlds are in a seperate folder, include the path. E.g. 'worlds/world1'
