leveling:
    exp-curve: 1.0 #set this to adjust the EXP curve (higher numbers equal longer ending levels)
    max-exp: 100000 #be cautious on changing this after it has been set)
    max-level: 50 #max level to master/change from PARENT to Child)
    exp-loss: 0.10 #exp loss on death, is taken from current LEVEL not ALL exp.
    pvp-exp-loss: 1.0 #exp loss multiplier used during pvp
    max-party-size: 6 #maximum party size
    party-exp-bonus: 1.0 #multiplier of how much bonus xp should be awarded overall to parties
    level-loss: false #allow level loss when players lose xp
    mastery-loss: false #allow mastery loss when players lose xp
    spawner-checks: false #allow xp adjustments when near a spawner if true
    spawner-radius: 7 #how close to the spawner the creature needs to be to limit xp
    spawner-exp-mult: .5 #if spawner-checks is true, all xp gained from killing is multiplied by this number. setting to 0 gives no xp.
    reset-on-death: false #Hardcore mode to reset all levels/exp on death
    pvp-range: 50 #Level that players must be within to PvP with each other
    dump-exp-file: false #Dumps a levels.txt file with the exp/level pairings 
classes:
    swap-cost: 0 #cost to swap
    old-swap-cost: 0 #cost to swap back to a class you already have xp in
    prof-swap-cost: 0 #cost to swap to a new profession
    old-prof-swap-cost: 0 #cost to swap back to an old profession
    master-swap-free: true #will allow for users to change back to their mastered class freely
    first-swap-free: true #toggles charging for the first class switch
    use-prefix: false #basic name prefixing of heroclass, may not work correctly
    reset-exp-on-change: true #will reset the exp if the player switches without mastering
    reset-master-on-change: false #will reset all xp including masteries if the player switches classes
    reset-prof-master-on-change: false #will reset all xp including masteries if the player switches professions
    reset-prof-on-pri-change: false #will reset the players profession whenever they change primary classes
    lock-till-master: false #Will make it so players can not switch classes until they have mastered their current class
    lock-at-max-level: false #Will not allow a player who is the highest tier to swap classes
properties:
    storage-type: yml #currently only supports yml
    economy: false #use of the cost system
    debug: false #use this at your own risk
    enchant-exp-mult: 3 #XP cost multiplier for enchants - set to 0 to disable
    global-cooldown: 1 #Seconds a hero must wait before using a second skill
    block-tracking-duration: 900000 #duration to track for no-exp
    max-tracked-blocks: 2000 #max blocks to track for no-exp
    food-heal-percent: .05 # .05 = 5% of Total HP regained when a player regains health from being full
    slow-while-casting: true #slows the skill caster while they are using a skill with a warmup
bed:
    enabled: true #Do you want players to heal in beds?
    interval: 15 #the seconds it takes to heal the healPercent
    percent: 5 #the percent amount of damage to heal.
mana:
    interval: 5 #time in seconds between regen ticks
    percent: 5 #the percent regenned each tick
hats:
    level: 1 #Level to use HATS!
    enabled: false
worlds:
    disabled: ['World1', 'World2', 'World3'] #If your worlds are in a seperate folder, include the path. E.g. 'worlds/world1'
