name: Heroes
main: com.herocraftonline.dev.heroes.Heroes
version: 1.4.3-b000
website: http://www.herocraftonline.com
authors: [Herocraft Coding, DThielke, Rigby, RightLegRed, Sleaker, Kainzo]
description: Experience, leveling, skills and class system for Minecraft developed by Herocraft Development.
depend: [ Vault ]
softdepend: [ Spout, ScrollingMenuSigns]
commands:
  heroes:
    aliases: ['hero']
    description: Heroes commands
    usage: /<command>
  party:
    aliases: ['p']
    description: Heroes command
    usage: /<command> <message>
  skill:
    aliases: ['hskill']
    description: Heroes command
    usage: /<command> <skill>
  skills:
    aliases: ['skilllist']
    description: Heroes command
    usage: /<command>
  hlevel:
    aliases: ['level','lvl']
    description: Display Hero level information
    usage: /<command>
  bind:
    description: Binds a skill to an item
    usage: /<command> <skill> 
  mana:
    aliases: [mp]
    description: Displays the hero's current mana
    usage: /<command>
  health:
    aliases: [hp]
    description: Displays the hero's health
    usage: /<command>
  cooldowns:
    aliases: [cd]
    description: Displays a list of the hero's cooldowns
    usage: /<command>
  party:
    aliases: ['p','pc']
    description: Chat with Heroes party members
    usage: /<command> <message>
permissions:
  heroes.admin.*:
    description: Gives access to administration commands for Heroes
    children:
      heroes.admin.class: true
      heroes.admin.level: true
      heroes.admin.health: true
      heroes.admin.exp: true
      heroes.admin.reload: true
      heroes.admin.saveall: true
      heroes.admin.prof: true